### PR TITLE
Properly validate 'max_public' as an integer

### PR DESCRIPTION
**Pull request by squigglezworth**

### CODE REVIEW

**Comment by dgw** [comment]
Hi @squigglezworth, thanks for this. It will be included in the next module release. I don't know if it will be just a patch with this and maybe another bugfix or two, or a bigger version bump, but I won't wait _too_ long for other things to include.

I skimmed your discussion on IRC, and yes, this PR adds the `parse` argument. It'd be cool if you changed the patch to do `parse=int`, for the sake of being explicit, but it's not a big deal. I'll merge the PR when the time comes, either way.

**Comment by squigglezworth** [comment]
Thanks for the info. I just changed it to reflect that. :)

**Comment by dgw** [comment]
Since it hasn't updated the PR status, I'm guessing GitHub won't recognize this as merged until I pull the maintenance branch into `master`. But it'll be in 0.4.1, probably out next week-ish. I'll leave the PR open to see if GitHub does pick it up eventually, for science. :smile_cat:

**Comment by dgw** [comment]
Meh, I guess GitHub couldn't follow the flow on this one. Even with the master branch fast-forwarded to include the merged commit, it still hasn't picked up on it.

If fake-merging it a second time doesn't work I'll probably just "close" this PR even though it's really merged.

**Edit:** I borked the patch branch trying to get clean history that GitHub might detect.

**Comment by dgw** [comment]
Yay, I fixed it. @squigglezworth This way the PR counts as "accepted" in your stats. :)

**Comment by squigglezworth** [comment]
:) Thank  you. Glad to have helped

**Pull request merged**
